### ISSUE TITLE
How to train on single gpu ?

### ISSUE THREAD

**Issue by mickey-cool** [OpenPerceptionX/PersFormer_3DLane#27]
I encountered this problem when I try to train on a single Gpu, please help me,Thank you :

python  main_persformer.py --mod=kkk  --batch_size=8 --nepochs=200

proc_id: None
world size: 1
local_rank: None
None
Traceback (most recent call last):
  File "main_persformer.py", line 40, in <module>
    main()
  File "main_persformer.py", line 30, in main
    ddp_init(args)
  File "/media/lee/PersFormer_3DLane-main/experiments/ddp.py", line 80, in ddp_init
    setup_distributed(args)
  File "/media/lee/PersFormer_3DLane-main/experiments/ddp.py", line 63, in setup_distributed
    torch.cuda.set_device(args.gpu)
  File "/media/lee/miniconda3/envs/cc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 309, in set_device
    device = _get_device_index(device)
  File "/media/lee/miniconda3/envs/cc/lib/python3.7/site-packages/torch/cuda/_utils.py", line 34, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
  File "/media/lee/miniconda3/envs/cc/lib/python3.7/site-packages/torch/_utils.py", line 514, in _get_device_index
    'or an integer, but got:{}'.format(device))
ValueError: Expected a torch.device with a specified index or an integer, but got:None

**Comment by callzhang** [comment]
Had the same issue, the code was written with distributed by default. Try to set `args.proc_id = 0` and `args.distributed = False`

**Comment by s95huang** [comment]
I simply used 
```
python -m torch.distributed.launch --nproc_per_node 1  main_persformer.py --mod=test --batch_size=8 --nepochs=100
```

**Comment by zihanding819** [comment]
set `--nproc_per_node` as 1 to use single gpu for training. Hope the script below could help you.
`
NUM_GPUS=1
EXPR_NAME=PersFormer
BATCH_SIZE=1
NUM_EPOCHS=1
python -m torch.distributed.launch
    --nproc_per_node $NUM_GPUS main_persformer.py
    --mod=$EXPR_NAME --batch_size=$BATCH_SIZE --nepochs=$NUM_EPOCHS
`
