### ISSUE TITLE
Data loader error

### ISSUE THREAD

**Issue by s95huang** [OpenPerceptionX/PersFormer_3DLane#41]
started training using ``` python main_persformer.py --mod=test  --batch_size=8 --nepochs=100 ``` 
and ``` python -m torch.distributed.launch --nproc_per_node 1  main_persformer.py --mod=test --batch_size=8 --nepochs=100```

Had the following problem
```
Let's use 1 GPUs!
Loading Dataset ...
Discarding images:
0
use default sampler
Traceback (most recent call last):
  File "main_persformer.py", line 40, in <module>
    main()
  File "main_persformer.py", line 32, in main
    runner = Runner(args)
  File "/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/experiments/runner.py", line 66, in __init__
    self.train_dataset, self.train_loader, self.train_sampler = self._get_train_dataset()
  File "/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/experiments/runner.py", line 529, in _get_train_dataset
    train_loader, train_sampler = get_loader(train_dataset, args)
ValueError: too many values to unpack (expected 2)
```

For the config:
I made the following changes:
```
      args.dataset_dir = '/mnt/0cb7d5a4-6618-47e1-b81a-2315ebd35b37/data/openlane/dataset/images/'
    args.data_dir = '/mnt/0cb7d5a4-6618-47e1-b81a-2315ebd35b37/data/openlane/dataset/lane3d_1000/'

  # ddp related
    args.dist = False
    args.sync_bn = False

    args.no_3d = True 

    args.proc_id = 0
    args.distributed = False
    args.gpu = 0
```
My dataset directory is shown below:
![image](https://user-images.githubusercontent.com/43658518/186539136-7cabf17b-2d45-4dce-a898-aed9addaeebc.png)

I tried the following debugging:
```       
        print("===> Training set size: {}".format(len(train_dataset)))
        print("===> args: {}".format(args))
        train_loader, train_sampler = get_loader(train_dataset, args)
```
and returned
```
===> Training set size: 157848
===> args: Namespace(K=array([[1000.,    0.,  960.],
       [   0., 1000.,  640.],
       [   0.,    0.,    1.]]), S=72, T_0=500, T_max=8, T_mult=1, _2d_prob_loss_weight=0.0, _2d_reg_loss_weight=0.0, _2d_vis_loss_weight=0.0, _3d_prob_loss_weight=0.0, _3d_reg_loss_weight=0.0, _3d_vis_loss_weight=0.0, _seg_loss_weight=0.0, anchor_feat_channels=64, anchor_grid_x=array([[-10.        , -10.        , -10.        , ..., -10.        ,
        -10.        , -10.        ],
       [ -8.66666667,  -8.66666667,  -8.66666667, ...,  -8.66666667,
         -8.66666667,  -8.66666667],
       [ -7.33333333,  -7.33333333,  -7.33333333, ...,  -7.33333333,
         -7.33333333,  -7.33333333],
       ...,
       [  8.13333333,  10.13333333,  12.13333333, ...,  30.13333333,
         38.13333333,  46.13333333],
       [  9.46666667,  11.46666667,  13.46666667, ...,  31.46666667,
         39.46666667,  47.46666667],
       [ 10.8       ,  12.8       ,  14.8       , ...,  32.8       ,
         40.8       ,  48.8       ]]), anchor_y_steps=array([  5,  10,  15,  20,  30,  40,  50,  60,  80, 100]), batch_norm=True, batch_size=8, cam_height=1.55, channels_in=3, clip_grad_norm=35.0, cls_loss_weight=1.0, conf_th=0.1, crop_y=0, cudnn=True, data_dir='/mnt/0cb7d5a4-6618-47e1-b81a-2315ebd35b37/data/openlane/dataset/lane3d_1000/', dataset_dir='/mnt/0cb7d5a4-6618-47e1-b81a-2315ebd35b37/data/openlane/dataset/images/', dataset_name='openlane', dist=False, distributed=False, encoder='EfficientNet-B3', eta_min=1e-05, evaluate=False, evaluate_case=False, feature_channels=128, fix_cam=False, fmap_mapping_interp_index=array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       ...,

       [[ 0,  0],
        [ 0,  1],
        [ 1,  2],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  1],
        [ 1,  2],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  1],
        [ 1,  2],
        ...,
        [14, 15],
        [ 0,  0],
        [ 0,  0]]]), fmap_mapping_interp_weight=array([[[0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]],

       ...,

       [[0.        , 0.        ],
        [0.92307692, 0.07692308],
        [0.92307692, 0.07692308],
        ...,
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.61538462, 0.38461538],
        [0.61538462, 0.38461538],
        ...,
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.30769231, 0.69230769],
        [0.30769231, 0.69230769],
        ...,
        [0.76923077, 0.23076923],
        [0.        , 0.        ],
        [0.        , 0.        ]]]), gamma=0.1, gpu=0, im_anchor_angles=[array([13.38774168, 15.35622435, 17.98113487, 21.63719831, 27.02231477,
       35.52769327, 13.78622136, 15.8795232 , 18.69578452, 22.66332033,
       28.59283131, 38.11915612, 13.01126367, 14.86556104, 17.31749166,
       20.69604962, 25.60419655, 33.22746829, 14.20864731, 16.43872893,
       19.46730566, 23.78571073, 30.33891954, 41.04801986, 12.65504408,
       14.40463831, 16.69974282, 19.83018921, 24.31883021, 31.17829495,
       15.13430285, 17.68020515, 21.20902922, 26.37446808, 34.47194144,
       48.12916757, 11.99726763, 13.56201687, 15.58458742, 18.29213003,
       22.08213108, 27.70021836]), array([144.47230673, 152.97768523, 158.36280169, 162.01886513,
       164.64377565, 166.61225832, 146.77253171, 154.39580345,
       159.30395038, 162.68250834, 165.13443896, 166.98873633,
       141.88084388, 151.40716869, 157.33667967, 161.30421548,
       164.1204768 , 166.21377864, 148.82170505, 155.68116979,
       160.16981079, 163.30025718, 165.59536169, 167.34495592,
       138.95198014, 149.66108046, 156.21428927, 160.53269434,
       163.56127107, 165.79135269, 152.29978164, 157.91786892,
       161.70786997, 164.41541258, 166.43798313, 168.00273237,
       131.87083243, 145.52805856, 153.62553192, 158.79097078,
       162.31979485, 164.86569715]), array([ 49.95934314,  74.35227124, 105.64772876, 130.04065686,
        54.463179  ,  81.24205062, 112.10451174, 134.01977512,
        45.98022488,  67.89548826,  98.75794938, 125.536821  ,
        59.53524673,  88.39554646, 118.02173207, 137.52859198,
        42.47140802,  61.97826793,  91.60445354, 120.46475327,
        71.42127671, 102.63034064, 128.10669722, 143.35910639,
        36.64089361,  51.89330278,  77.36965936, 108.57872329])], im_anchor_origins=[array([0.65867168, 0.68308271, 0.71637048, 0.76445281, 0.84001075,
       0.97601505, 0.64653957, 0.66989249, 0.7020996 , 0.74937436,
       0.8255192 , 0.96860456, 0.67009707, 0.69539032, 0.72951963,
       0.77809521, 0.85275164, 0.98220179, 0.63363307, 0.65572118,
       0.68655705, 0.73262052, 0.80888955, 0.95956738, 0.68087574,
       0.70690103, 0.74167431, 0.7904974 , 0.86404105, 0.98744479,
       0.60518009, 0.62396225, 0.65091057, 0.69283017, 0.76699562,
       0.93386788, 0.70070079, 0.72782252, 0.76341979, 0.81220123,
       0.88315605, 0.99584901]), array([0.97601505, 0.84001075, 0.76445281, 0.71637048, 0.68308271,
       0.65867168, 0.98220179, 0.85275164, 0.77809521, 0.72951963,
       0.69539032, 0.67009707, 0.96860456, 0.8255192 , 0.74937436,
       0.7020996 , 0.66989249, 0.64653957, 0.98744479, 0.86404105,
       0.7904974 , 0.74167431, 0.70690103, 0.68087574, 0.95956738,
       0.80888955, 0.73262052, 0.68655705, 0.65572118, 0.63363307,
       0.99584901, 0.88315605, 0.81220123, 0.76341979, 0.72782252,
       0.70070079, 0.93386788, 0.76699562, 0.69283017, 0.65091057,
       0.62396225, 0.60518009]), array([0.18488391, 0.3949613 , 0.6050387 , 0.81511609, 0.18006799,
       0.39014538, 0.60022278, 0.81030017, 0.18969983, 0.39977722,
       0.60985462, 0.81993201, 0.17525207, 0.38532946, 0.59540686,
       0.80548425, 0.19451575, 0.40459314, 0.61467054, 0.82474793,
       0.16562023, 0.37569762, 0.58577501, 0.79585241, 0.20414759,
       0.41422499, 0.62430238, 0.83437977])], ipm_h=208, ipm_w=128, lane_width=2, learnable_weight_on=True, learning_rate=0.0002, local_rank=None, loss_att_weight=100.0, loss_dist=[10.0, 4.0, 1.0], loss_seg_weight=0.0, loss_threshold=100000.0, lr_decay=False, lr_decay_iters=10, lr_policy='cosine', match_dist_thre_3d=2.0, max_lanes=20, mod='bruce_persformer_2d_only', nepochs=100, new_match=False, nhead=8, niter=900, niter_decay=400, nms_thres=45.0, nms_thres_3d=1.0, no_3d=True, no_centerline=True, no_cuda=False, no_tb=False, npoints=8, num_att=3, num_category=21, num_class=2, num_proj=4, num_y_steps=10, nworkers=4, optimizer='adam', org_h=1280, org_w=1920, pitch=3, port=29666, position_embedding='learned', pred_cam=False, pretrained=False, print_freq=10, prob_th=0.5, proc_id=0, reg_vis_loss_weight=1.0, resize_h=360, resize_w=480, resume='', save_freq=50, save_json_path='/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/data_splits/openlane', save_path='/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/data_splits/openlane/bruce_persformer_2d_only', save_prefix='/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/data_splits', seg_start_epoch=1, start_epoch=0, sync_bn=False, test_mode=False, top_view_region=array([[-10, 103],
       [ 10, 103],
       [-10,   3],
       [ 10,   3]]), use_att=True, use_default_anchor=False, use_fpn=False, use_memcache=False, use_proj=True, use_slurm=False, use_top_pathway=False, vgg_mean=[0.485, 0.456, 0.406], vgg_std=[0.229, 0.224, 0.225], vis_th=0.1, weight_decay=0.001, weight_init='normal', world_size=1, y_ref=5)
Discarding images:
0
use default sampler
Traceback (most recent call last):
  File "main_persformer.py", line 40, in <module>
    main()
  File "main_persformer.py", line 32, in main
    runner = Runner(args)
  File "/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/experiments/runner.py", line 66, in __init__
    self.train_dataset, self.train_loader, self.train_sampler = self._get_train_dataset()
  File "/home/almon/personal_repos/Camera/lane/PersFormer_3DLane/experiments/runner.py", line 531, in _get_train_dataset
    train_loader, train_sampler = get_loader(train_dataset, args)

```

**Comment by ilnehc** [comment]
@s95huang It is resulting from when you set `args.dist=False`:
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/584cf52ae07ea1288fc67f75cf1f0e2688885769/data/Load_Data.py#L1927-L1929
You could try to fix it and raise a PR, or you could simply not modify the ddp args.
