### ISSUE TITLE
training problem with torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by betterCZ101** [OpenPerceptionX/PersFormer_3DLane#78]
hello,  when I training with
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node 1 main_persformer.py --batch_size=2 --nepochs=100 --mod=PersFormer, I meet the problem that is :
`
Traceback (most recent call last):
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/data2/anaconda3/envs/persformer/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: `

main_persformer.py FAILED

How can I solve this problem? Thank you!

**Comment by betterCZ101** [comment]
ok.thanks
